import mongoose from "mongoose";
import dotenv from "dotenv";
import Product from "./models/Product.js";

dotenv.config();

const products = [
  {
    title: "Trendy Farshi Salwar-5965 - Maroon",
    slug: "trendy-farshi-salwar-5965-maroon",
    sku: "5965",
    price: 2299,
    images: ["https://placehold.co/600x800/7a1f2b/fff?text=Farshi+Salwar+Maroon"],
    type: "Unstitched",
    fabric: "Lawn",
    dupatta: "Chiffon",
    colors: [
      { name: "Maroon", hex: "#7a1f2b" },
      { name: "Blue", hex: "#1c4e9e" },
      { name: "Orange", hex: "#e08a1e" },
    ],
    sizes: ["Unstitched"],
    categories: ["new-drop", "festive-wear"],
    soldOut: true,
    isNew: false,
    description: "Trendy embroidered farshi salwar suit, unstitched, festive wear.",
  },
  {
    title: "Trendy Black & White Farshi Salwar (6-8 Days Dispatching Time) - White",
    slug: "trendy-black-white-farshi-salwar-white",
    sku: "4410",
    price: 2599,
    images: ["https://placehold.co/600x800/eeeeee/222?text=Black+White+Farshi"],
    type: "Unstitched",
    fabric: "Lawn",
    dupatta: "Chiffon",
    colors: [
      { name: "White", hex: "#f5f5f5" },
      { name: "Black", hex: "#111111" },
    ],
    sizes: ["Unstitched"],
    categories: ["new-drop", "party-wear"],
    soldOut: false,
    isNew: true,
    description: "Trendy black & white embroidered farshi salwar suit.",
  },
  {
    title: "Stunning Black&Yellow Embroidered Suit 3803/1305",
    slug: "stunning-black-yellow-embroidered-suit-3803-1305",
    sku: "3803",
    price: 1099,
    images: ["https://placehold.co/600x800/111827/f5c518?text=Black+Yellow+Suit"],
    type: "Unstitched",
    fabric: "Lawn",
    dupatta: "Chiffon",
    colors: [{ name: "Black", hex: "#111111" }],
    sizes: ["Unstitched"],
    categories: ["new-drop", "readymade"],
    soldOut: true,
    isNew: false,
    description: "Stunning black & yellow embroidered unstitched suit.",
  },
  {
    title: "Embroidered Flower Charm Pak-Suit 1359",
    slug: "embroidered-flower-charm-pak-suit-1359",
    sku: "1359",
    price: 1099,
    images: ["https://placehold.co/600x800/e7d9c2/6b3f2a?text=Flower+Charm+Suit"],
    type: "Unstitched",
    fabric: "Lawn",
    dupatta: "Cotton",
    colors: [{ name: "Beige", hex: "#e7d9c2" }],
    sizes: ["Unstitched"],
    categories: ["daily-wear", "readymade"],
    soldOut: true,
    isNew: false,
    description: "Embroidered floral charm Pakistani lawn suit.",
  },
  {
    title: "Printed Pakistani Cotton Suit With Chiffon Dupatta-1358",
    slug: "printed-pakistani-cotton-suit-chiffon-dupatta-1358",
    sku: "1358",
    price: 1099,
    images: ["https://placehold.co/600x800/f4ede1/8a5a3b?text=Printed+Cotton+Suit"],
    type: "Unstitched",
    fabric: "Cotton",
    dupatta: "Chiffon",
    colors: [{ name: "Cream", hex: "#f4ede1" }],
    sizes: ["Unstitched"],
    categories: ["daily-wear"],
    soldOut: true,
    isNew: false,
    description: "Printed Pakistani cotton suit with matching chiffon dupatta.",
  },
  {
    title: "Timeless White & Blue Unstitched Ensemble 1330",
    slug: "timeless-white-blue-unstitched-ensemble-1330",
    sku: "1330",
    price: 1099,
    images: ["https://placehold.co/600x800/e9eef5/2e4c7a?text=White+Blue+Ensemble"],
    type: "Unstitched",
    fabric: "Lawn",
    dupatta: "Chiffon",
    colors: [{ name: "White", hex: "#f5f5f5" }],
    sizes: ["Unstitched"],
    categories: ["festive-wear"],
    soldOut: true,
    isNew: false,
    description: "Timeless white & blue embroidered unstitched ensemble.",
  },
  {
    title: "Daily Wear Cotton Printed Suit Set",
    slug: "daily-wear-cotton-printed-suit-set",
    sku: "6601",
    price: 1399,
    images: ["https://placehold.co/600x800/bcb31a/222?text=Cotton+Printed+Set"],
    type: "Stitched",
    fabric: "Cotton",
    dupatta: "Cotton",
    colors: [{ name: "Olive", hex: "#bcb31a" }],
    sizes: ["M", "L", "XL", "XXL"],
    categories: ["ready-to-wear", "daily-wear"],
    soldOut: false,
    isNew: true,
    description: "Daily wear cotton printed suit set, comfortable everyday wear.",
  },
  {
    title: "Red Embroidered Three Piece Set",
    slug: "black-multicolor-embroidered-suit-set-lrc-377-copy",
    sku: "7092",
    price: 2499,
    images: [
      "https://placehold.co/600x800/e9e0d3/8a1f2b?text=Red+Embroidered+Set+1",
      "https://placehold.co/600x800/e9e0d3/8a1f2b?text=Red+Embroidered+Set+2",
      "https://placehold.co/600x800/e9e0d3/8a1f2b?text=Red+Embroidered+Set+3",
    ],
    type: "Stitched/Ready to Wear",
    fabric: "Cotton",
    dupatta: "Cotton",
    colors: [{ name: "Red", hex: "#8a1f2b" }],
    sizes: ["Free Size Upto 44"],
    categories: ["ready-to-wear", "party-wear"],
    soldOut: false,
    isNew: true,
    description:
      "Cotton 3-pc suit featuring heavy red thread embroidery on neckline, sleeves, and daman with lace insertion details and tassels on the neck. Comes with matching cotton pants with embroidered border and a soft printed dupatta.",
  },
  {
    title: "Premium Heavy Handworked Suit - Navy Blue",
    slug: "premium-heavy-handworked-suit-navy-blue",
    sku: "9910",
    price: 15999,
    images: ["https://placehold.co/600x800/16213e/d8c98a?text=Navy+Handworked+Suit"],
    type: "Stitched",
    fabric: "Organza",
    dupatta: "Organza",
    colors: [
      { name: "Blue", hex: "#16213e" },
      { name: "White", hex: "#f5f5f5" },
      { name: "Black", hex: "#111111" },
    ],
    sizes: ["S", "M", "L", "XL"],
    categories: ["ready-to-wear", "celebrity-look", "luxe"],
    soldOut: false,
    isNew: true,
    description: "Premium heavy handworked suit with intricate embellishments.",
  },
  {
    title: "Floral Embroidered Farshi Salwar T1128 - Blue",
    slug: "floral-embroidered-farshi-salwar-t1128-blue",
    sku: "1128",
    price: 2699,
    images: ["https://placehold.co/600x800/c8e0d8/2e6b52?text=Floral+Farshi+Salwar"],
    type: "Stitched",
    fabric: "Cotton",
    dupatta: "Cotton",
    colors: [
      { name: "Blue", hex: "#5aa0c8" },
      { name: "Yellow", hex: "#e6c62f" },
    ],
    sizes: ["M", "L", "XL"],
    categories: ["ready-to-wear", "festive-wear"],
    soldOut: false,
    isNew: true,
    description: "Floral embroidered farshi salwar suit in fresh mint & blue.",
  },
];

async function run() {
  await mongoose.connect(process.env.MONGODB_URI);
  await Product.deleteMany({});
  await Product.insertMany(products);
  console.log(`Seeded ${products.length} products`);
  process.exit(0);
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
